import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Update from "../Components/update_address";
const Update_address_page = (props: any) => {
  // =============================================================
  const router = useRouter();
  const { state } = router.query;
  // React.useEffect(() => {
  //   console.log("testing:::", state);
  // }, []);
  React.useEffect(() => {
    console.log("testing:::", state);
  }, [state]);
  const [address, setaddress] = useState(
    typeof state === "string" ? JSON.parse(state) : {}
  );
  // ================================================================

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&display=swap"
          rel="stylesheet"
        ></link> */}
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        />
        {/* <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        /> */}
      </Head>

      {address.id && <Update addressProp={address} />}
    </>
  );
};

export default Update_address_page;
